import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  Ban,
  BellRing,
  Bold,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  Circle,
  Clapperboard,
  ClipboardList,
  Clock,
  Copy,
  DoorOpen,
  ExternalLink,
  Eye,
  FileText,
  Gamepad2,
  GraduationCap,
  Heading2,
  Heading3,
  Heart,
  House,
  HouseHeart,
  Image as ImageIcon,
  Info,
  Italic,
  Key,
  LayoutDashboard,
  List,
  ListOrdered,
  LoaderCircle,
  LocateFixed,
  Mail,
  Map as MapIcon,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Music,
  Palette,
  Pencil,
  Phone,
  Plug,
  Plus,
  Quote,
  Redo2,
  Repeat,
  Rss,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  TentTree,
  Undo2,
  UserRound,
  UserX,
  UsersRound,
  Volleyball,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";

const REGISTRY = {
  accessibility: Accessibility,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  ban: Ban,
  "bell-ring": BellRing,
  bold: Bold,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  circle: Circle,
  clapperboard: Clapperboard,
  "clipboard-list": ClipboardList,
  clock: Clock,
  copy: Copy,
  "door-open": DoorOpen,
  "external-link": ExternalLink,
  eye: Eye,
  "file-text": FileText,
  "gamepad-2": Gamepad2,
  "graduation-cap": GraduationCap,
  "heading-2": Heading2,
  "heading-3": Heading3,
  heart: Heart,
  house: House,
  "house-heart": HouseHeart,
  image: ImageIcon,
  info: Info,
  italic: Italic,
  key: Key,
  "layout-dashboard": LayoutDashboard,
  list: List,
  "list-ordered": ListOrdered,
  "loader-circle": LoaderCircle,
  "locate-fixed": LocateFixed,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  palette: Palette,
  pencil: Pencil,
  phone: Phone,
  plug: Plug,
  plus: Plus,
  quote: Quote,
  redo: Redo2,
  repeat: Repeat,
  rss: Rss,
  search: Search,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  tag: Tag,
  "tent-tree": TentTree,
  undo: Undo2,
  user: UserRound,
  "user-x": UserX,
  "users-round": UsersRound,
  volleyball: Volleyball,
  wallet: Wallet,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

export function Icon({
  name,
  size = 20,
  className,
  color,
  fill,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  className?: string;
  color?: string;
  fill?: string;
  strokeWidth?: number;
}) {
  const Cmp = REGISTRY[name];
  return (
    <Cmp
      size={size}
      className={className}
      color={color}
      fill={fill}
      strokeWidth={strokeWidth}
      aria-hidden="true"
    />
  );
}
